/**
 * Regenerates the theme variants of the SearchApi wordmark from the vendor
 * original, so that recolouring a logo is never done by hand in an editor.
 *
 * Run: `node logo/derive.mjs`
 *
 * Why variants exist at all: the site inlines the geometry with
 * `fill="currentColor"` and inherits whatever ink the surrounding chrome
 * carries, which is the right answer everywhere CSS reaches. GitHub is not
 * such a place — a README image is an <img>, `currentColor` there resolves
 * against the SVG's own initial value (black) rather than the page, so a
 * single file would render black-on-near-black for every reader using the
 * dark theme. Hence two files and a <picture> element in README.md.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const raw = readFileSync(join(here, "search-api.svg"), "utf8");

const drawables = [];
const re = /<(path|polygon)\b([^>]*?)\/?>/g;
let m;
while ((m = re.exec(raw))) {
  const [, tag, attrs] = m;
  const id = /\bid="([^"]*)"/.exec(attrs)?.[1] ?? null;
  const geomAttr = tag === "path" ? "d" : "points";
  drawables.push({
    tag,
    id,
    geomAttr,
    geom: new RegExp(`\\b${geomAttr}="([^"]*)"`).exec(attrs)?.[1] ?? "",
  });
}

/*
 * `path-1` is the only drawable that is not ink. It lives in <defs> and exists
 * solely to feed Sketch's `mask-2`, whose rect is 0,0 → 426.31,87.66 — larger
 * than every shape it masks, so it clips nothing. Dropping the mask, the
 * <defs> and the <use> is a no-op on the rendered result and removes the one
 * thing that would otherwise collide if two copies met on the same page:
 * duplicate element ids.
 */
const ink = drawables.filter((d) => d.id !== "path-1");
if (ink.length !== 16)
  throw new Error(`expected 16 shapes, found ${ink.length}`);

/*
 * Coordinate precision. Both call sites size the mark at 18px tall, so it
 * renders 87px wide from a 427-unit viewBox: one user unit is 0.2px, and two
 * decimals resolve to 0.002px — two orders of magnitude below a device pixel
 * even on a 3x display. It costs nothing visible and returns close to half the
 * bytes, which matters because this geometry ships inline in the HTML of every
 * page rather than as one cached request.
 */
const round = (s) =>
  s.replace(/-?\d*\.\d+/g, (n) =>
    String(Math.round(parseFloat(n) * 100) / 100),
  );
const shapes = ink.map((d) => ({ ...d, geom: round(d.geom) }));

/*
 * Two corrections to the vendor file, both deliberate.
 *
 * `fill-rule="evenodd"` is carried over from the wrapping <g> Sketch put it
 * on. Measured, it makes no difference to this artwork — the four letters with
 * counters (a, e, p, and the A of the wordmark) wind their inner subpath
 * against the outer one, so `nonzero` agrees with `evenodd` pixel for pixel.
 * It is kept anyway because it is what the source declares, and a future
 * vendor update could ship counters that wind the other way; inheriting the
 * rule means that update cannot silently fill them in.
 *
 * The intrinsic size is rewritten to match the viewBox, and that one is a real
 * bug fix. The original declares width="257.2589683389664"
 * height="63.92396926879883" — an aspect of 4.02 against the viewBox's 4.85 —
 * so under the default `preserveAspectRatio` it letterboxes its own artwork to
 * 83% height anywhere the intrinsic size is honoured, which includes an <img>
 * in a README. Measured: 118,969 ink pixels against 143,359 for the same
 * geometry given a viewport that agrees with it.
 */
const render = (fill, note) => `<!--
  SearchApi's wordmark — a trademark of SearchApi, not of this project.
  See logo/README.md for what that permits.

  GENERATED by logo/derive.mjs from logo/search-api.svg. Do not hand-edit.
  ${note}
-->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 427 88" width="427" height="88" fill="${fill}" fill-rule="evenodd" role="img" aria-label="SearchApi">
  <title>SearchApi</title>
${shapes.map((d) => `  <${d.tag} ${d.geomAttr}="${d.geom}" />`).join("\n")}
</svg>
`;

writeFileSync(
  join(here, "search-api-light.svg"),
  render("#000000", "Ink for a light background — GitHub's light theme."),
);
writeFileSync(
  join(here, "search-api-dark.svg"),
  render("#ffffff", "Ink for a dark background — GitHub's dark theme."),
);

// The web component keeps its own copy of this geometry, because it needs
// `currentColor` and JSX camelCase rather than a file. Print it so that
// re-syncing it after a vendor logo update is a paste, not a transcription.
console.log(`wrote 2 variants from ${shapes.length} shapes\n`);
console.log("--- JSX body for packages/web/components/search-api-logo.tsx ---");
console.log(
  shapes.map((d) => `      <${d.tag} ${d.geomAttr}="${d.geom}" />`).join("\n"),
);
